### ISSUE TITLE
Issue with nested symbol

### ISSUE THREAD

**Issue by kundugoutam** [cjgammon/Flash-Plugin-SnapPlatform#15]
A shape within a nested symbol is not being rendered properly (Refer SampleExample1.fla)

**Comment by cjgammon** [comment]
this is actually an issue in how we're handling single frame movieclips combined with the fact that upon repeat of the movie clip the SVG canvas is completely cleared, resulting in a visible flicker.  Perhaps the solution would be creating a special case for single frame movieclips so they don't loop.

**Comment by cjgammon** [comment]
I made a fix that no longer does the place command on a movie clip if it is already placed, this seems to fix all the examples we have of single frame movieclips and nested timelines.
