### ISSUE TITLE
No alpha?

### ISSUE THREAD

**Issue by fakepilot** [cjgammon/Flash-Plugin-SnapPlatform#23]
During my export, there was no alpha on animation that normally had some!

**Comment by cjgammon** [comment]
Thanks for the heads up! I've added alpha support to movieclips.

**Comment by fakepilot** [comment]
Great! Did you add it to Graphic Instances too?

Very often use Graphic clips instead of Movieclips so their animation can be viewed in the main timeline. Also, often import text animation as SWF to Flash from After Effects. That is always imported as Graphic, not movieclips. :-)

**Comment by cjgammon** [comment]
it is implemented for both.
