### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by cjgammon** [cjgammon/Flash-Plugin-SnapPlatform#7]
let's expose masks in the JSON so we can do awesome masked animations.

**Comment by kundugoutam** [comment]
Added masking information in the JSON. JSON contains the following information:

objectId: Object Identifier of the mask object
maskTill: Object Id of the lowest object that is masked by the mask object. The mask will
              have effect on all the objects after the mask object till the object with the id         
              lowestMaskedObjectId. If lowestMaskedObjectId is same as maskObjectId,then the 
              mask has no effect.

Have not generated the binaries or the zxp with this change yet.
